import React, { createContext, useContext, useState, useEffect } from 'react';
import { View, ActivityIndicator } from 'react-native';

let AsyncStorage;
try {
  AsyncStorage = require('@react-native-async-storage/async-storage').default;
} catch (e) {
  // AsyncStorage not available, use in-memory fallback
  AsyncStorage = {
    getItem: async () => null,
    setItem: async () => {},
  };
}

const LanguageContext = createContext();

const STORAGE_KEY = '@app_language';

// Languages object - similar to currencies, for use in LanguageSelector
const languages = {
  en: { nativeName: 'English', englishName: 'English' },
  sr: { nativeName: 'Srpski', englishName: 'Serbian' },
  es: { nativeName: 'Español', englishName: 'Spanish' },
  pt: { nativeName: 'Português', englishName: 'Portuguese' },
  fr: { nativeName: 'Français', englishName: 'French' },
  de: { nativeName: 'Deutsch', englishName: 'German' },
  it: { nativeName: 'Italiano', englishName: 'Italian' },
  ar: { nativeName: 'العربية', englishName: 'Arabic' },
};

const translations = {
  en: {
            // Screen titles
            'screen.addExpense': 'Add Expense',
            'screen.editExpense': 'Edit Expense',
            'screen.addIncome': 'Add Income',
            'screen.editIncome': 'Edit Income',
            'screen.scanReceipt': 'Scan Receipt',
            'screen.reviewReceipt': 'Review Receipt',
            'screen.dashboard': 'Dashboard',
            'screen.categoryBreakdown': 'Category Breakdown',
    
    // Labels
    'label.amount': 'Amount',
    'label.date': 'Date',
    'label.merchant': 'Merchant',
    'label.category': 'Category',
    'label.description': 'Description',
    
            // Buttons
            'button.submit': 'Submit',
            'button.saveChanges': 'Save changes',
            'button.addExpense': 'Add Expense',
            'button.addIncome': 'Add Income',
            'button.scanReceipt': 'Scan receipt (coming soon)',
            'button.ok': 'OK',
            'button.selectCategory': 'Select a category',
            'button.deleteExpense': 'Delete Expense',
            'button.deleteIncome': 'Delete Income',
            'button.delete': 'Delete',
            'button.cancel': 'Cancel',
            'button.overview': 'Overview',
            'button.income': 'Income',
            'button.expenses': 'Expenses',
    
            // Messages
            'message.expenseAdded': 'Expense added successfully!',
            'message.expenseUpdated': 'Expense updated',
            'message.expenseDeleted': 'Expense deleted successfully',
            'message.deletingExpense': 'Deleting expense...',
            'message.confirmDelete': 'Are you sure you want to delete this expense? This action cannot be undone.',
            'message.confirmDeleteIncome': 'Are you sure you want to delete this income? This action cannot be undone.',
            'message.incomeAdded': 'Income added successfully!',
            'message.incomeUpdated': 'Income updated',
            'message.incomeDeleted': 'Income deleted successfully',
            'message.deletingIncome': 'Deleting income...',
            'message.success': 'Success',
            'message.loadingExpense': 'Loading expense...',
            'message.loadingIncome': 'Loading income...',
            'message.failedToCreate': 'Failed to create expense',
            'message.failedToUpdate': 'Failed to update expense',
            'message.failedToDelete': 'Failed to delete expense',
            'message.failedToLoad': 'Failed to load expense',
            'message.failedToCreateIncome': 'Failed to create income',
            'message.failedToUpdateIncome': 'Failed to update income',
            'message.failedToDeleteIncome': 'Failed to delete income',
            'message.failedToLoadIncome': 'Failed to load income',
    
    // Validation errors
            'error.invalidAmount': 'Please enter a valid amount greater than 0',
            'error.selectCategory': 'Please select a category',
            'error.selectDate': 'Please select a date',
            'error.acceptTerms': 'You must accept the Terms of Service and Privacy Policy to sign up',
    
            // Dashboard
            'dashboard.currentMonthTotal': 'Current Month Total',
            'dashboard.netIncome': 'Net Income',
            'dashboard.totalIncome': 'Total Income',
            'dashboard.totalExpenses': 'Total Expenses',
            'dashboard.monthComparison': 'Month Comparison',
            'dashboard.last6Months': 'Last 6 Months',
            'dashboard.recentExpenses': 'Recent Expenses',
            'dashboard.recentIncome': 'Recent Income',
            'dashboard.monthlyTotals': 'Monthly Totals',
            'dashboard.noExpenses': 'No expenses yet',
            'dashboard.noIncome': 'No income yet',
            'dashboard.noMonthlyData': 'No monthly data yet',
            'dashboard.error': 'Error',
            'dashboard.tapForDetails': 'Tap for category breakdown',
            'dashboard.categoryBreakdown': 'Category Breakdown',
            'dashboard.categoryDetails': 'Category Details',
            'dashboard.tap': 'Tap',
            'dashboard.total': 'Total',
            'dashboard.noData': 'No data',
    
    // Receipt Scanning
            'receipt.scanReceipt': 'Scan Receipt',
            'receipt.reviewReceipt': 'Review Receipt',
            'receipt.processing': 'Processing receipt...',
            'receipt.reviewData': 'Review Extracted Data',
            'receipt.useThisData': 'Use This Data',
            'receipt.retake': 'Retake',
            'receipt.process': 'Process',
            'receipt.preview': 'Preview',
            'receipt.error': 'Error',
            'receipt.captureError': 'Failed to capture image',
            'receipt.processingError': 'Failed to process receipt',
            'receipt.extractionFailed': 'Failed to extract data from receipt',
            'receipt.noData': 'No data extracted',
            'receipt.retry': 'Retry',
            'receipt.requestingPermission': 'Requesting camera permission...',
            'receipt.cameraPermissionDenied': 'Camera permission denied. Please enable it in settings.',
            'receipt.requestPermission': 'Request Permission',
            'receipt.galleryPermissionDenied': 'Gallery permission denied. Please enable it in settings.',
            'receipt.galleryError': 'Failed to pick image from gallery',
            'receipt.pickFromGallery': 'Pick from Gallery',
            'receipt.selectReceiptPhoto': 'Select Receipt Photo',
            'receipt.webCameraNotSupported': 'Camera is not supported on web. Please use "Pick from Gallery" to select an image.',
            'receipt.merchantPlaceholder': 'Store or merchant name',
            'receipt.descriptionPlaceholder': 'Optional description',
    
    // Expense Categories
    'category.groceries': 'Groceries',
    'category.utilities': 'Utilities',
    'category.transportation': 'Transportation',
    'category.housing': 'Housing',
    'category.healthcare': 'Healthcare',
    'category.education': 'Education',
    'category.entertainment': 'Entertainment',
    'category.diningOut': 'Dining Out',
    'category.clothing': 'Clothing',
    'category.personalCare': 'Personal Care',
    'category.giftsDonations': 'Gifts & Donations',
    'category.travel': 'Travel',
    'category.loansDebt': 'Loans & Debt Payments',
    'category.bankFees': 'Bank Fees & Overdrafts',
    'category.insurance': 'Insurance',
    'category.taxes': 'Taxes',
    'category.other': 'Other',
    
    // Income Categories
    'category.salary': 'Salary',
    'category.freelance': 'Freelance',
    'category.investment': 'Investment',
    'category.gift': 'Gift',
    'category.bonus': 'Bonus',
    'category.otherIncome': 'Other',
    
    // Placeholders
    'placeholder.amount': '0.00',
    'placeholder.description': 'Optional description',
    
            // Authentication
            'auth.login': 'Login',
            'auth.signup': 'Sign Up',
            'auth.email': 'Email',
            'auth.emailPlaceholder': 'your@email.com',
            'auth.username': 'Username (optional)',
            'auth.usernamePlaceholder': 'username',
            'auth.loginIdentifier': 'Email or Username',
            'auth.loginIdentifierPlaceholder': 'email or username',
            'auth.password': 'Password',
            'auth.passwordPlaceholder': 'Enter password',
            'auth.name': 'Name',
            'auth.namePlaceholder': 'Your name',
            'auth.haveAccount': 'Already have an account? Login',
            'auth.noAccount': "Don't have an account? Sign Up",
            'auth.forgotPassword': 'Forgot password?',
            'auth.resetPassword': 'Reset Password',
            'auth.resetPasswordTitle': 'Reset Your Password',
            'auth.resetPasswordMessage': 'Enter your email address and we will send you instructions to reset your password.',
            'auth.resetPasswordSent': 'If an account exists with this email, password reset instructions have been sent.',
            'auth.backToLogin': 'Back to Login',
            'auth.acceptTerms1': 'I agree to the',
            'auth.termsOfService': 'Terms of Service',
            'auth.and': 'and',
            'auth.privacyPolicy': 'Privacy Policy',
            'auth.deleteAccount': 'Delete Account',
            'auth.confirmDeleteAccount': 'Are you sure you want to delete your account? This will permanently delete all your data including all expenses. This action cannot be undone.',
            'auth.failedToDeleteAccount': 'Failed to delete account. Please try again.',
            'auth.error': 'Error',
            
            // Settings
            'screen.settings': 'Settings',
            'settings.openSettings': 'Open Settings',
            'settings.selectLanguage': 'Select Language',
            'settings.accountInfo': 'Account Information',
            'settings.name': 'Name',
            'settings.email': 'Email',
            'settings.username': 'Username',
            'settings.changePassword': 'Change Password',
            'settings.currentPassword': 'Current Password',
            'settings.currentPasswordPlaceholder': 'Enter current password',
            'settings.newPassword': 'New Password',
            'settings.newPasswordPlaceholder': 'Enter new password',
            'settings.confirmPassword': 'Confirm New Password',
            'settings.confirmPasswordPlaceholder': 'Confirm new password',
            'settings.passwordChanged': 'Password changed successfully',
            'settings.failedToChangePassword': 'Failed to change password',
            'settings.invalidCurrentPassword': 'Current password is incorrect',
            'settings.passwordTooShort': 'Password must be at least 6 characters',
            'settings.passwordsDoNotMatch': 'New passwords do not match',
            'settings.newPasswordSame': 'New password must be different from current password',
            'settings.fillAllFields': 'Please fill in all fields',
            'settings.networkError': 'Cannot connect to backend. Make sure the backend is running.',
            'settings.dangerZone': 'Danger Zone',
            'settings.deleteAccountWarning': 'Once you delete your account, there is no going back. Please be certain.',
  },
  sr: {
            // Screen titles
            'screen.addExpense': 'Dodaj Rashod',
            'screen.editExpense': 'Izmeni Rashod',
            'screen.addIncome': 'Dodaj Prihod',
            'screen.editIncome': 'Izmeni Prihod',
            'screen.scanReceipt': 'Skeniraj Račun',
            'screen.reviewReceipt': 'Pregled Računa',
            'screen.dashboard': 'Kontrolna Tabla',
            'screen.categoryBreakdown': 'Pregled po Kategorijama',
    
    // Labels
    'label.amount': 'Iznos',
    'label.date': 'Datum',
    'label.merchant': 'Trgovac',
    'label.category': 'Kategorija',
    'label.description': 'Opis',
    
    // Buttons
    'button.submit': 'Pošalji',
    'button.saveChanges': 'Sačuvaj izmene',
    'button.addExpense': 'Dodaj Rashod',
    'button.addIncome': 'Dodaj Prihod',
    'button.scanReceipt': 'Skeniraj račun (uskoro)',
    'button.ok': 'OK',
    'button.selectCategory': 'Izaberi kategoriju',
    'button.deleteExpense': 'Obriši Rashod',
    'button.deleteIncome': 'Obriši Prihod',
    'button.delete': 'Obriši',
    'button.cancel': 'Otkaži',
    'button.overview': 'Pregled',
    'button.income': 'Prihod',
    'button.expenses': 'Rashodi',
    
            // Messages
            'message.expenseAdded': 'Rashod je uspešno dodat!',
            'message.expenseUpdated': 'Rashod je ažuriran',
            'message.expenseDeleted': 'Rashod je uspešno obrisan',
            'message.deletingExpense': 'Brisanje rashoda...',
            'message.confirmDelete': 'Da li ste sigurni da želite da obrišete ovaj rashod? Ova akcija se ne može poništiti.',
            'message.confirmDeleteIncome': 'Da li ste sigurni da želite da obrišete ovaj prihod? Ova akcija se ne može poništiti.',
            'message.incomeAdded': 'Prihod je uspešno dodat!',
            'message.incomeUpdated': 'Prihod je ažuriran',
            'message.incomeDeleted': 'Prihod je uspešno obrisan',
            'message.deletingIncome': 'Brisanje prihoda...',
            'message.success': 'Uspeh',
            'message.loadingExpense': 'Učitavanje rashoda...',
            'message.loadingIncome': 'Učitavanje prihoda...',
            'message.failedToCreate': 'Neuspešno kreiranje rashoda',
            'message.failedToUpdate': 'Neuspešno ažuriranje rashoda',
            'message.failedToDelete': 'Neuspešno brisanje rashoda',
            'message.failedToLoad': 'Neuspešno učitavanje rashoda',
            'message.failedToCreateIncome': 'Neuspešno kreiranje prihoda',
            'message.failedToUpdateIncome': 'Neuspešno ažuriranje prihoda',
            'message.failedToDeleteIncome': 'Neuspešno brisanje prihoda',
            'message.failedToLoadIncome': 'Neuspešno učitavanje prihoda',
    
    // Validation errors
            'error.invalidAmount': 'Molimo unesite važeći iznos veći od 0',
            'error.selectCategory': 'Molimo izaberite kategoriju',
            'error.selectDate': 'Molimo izaberite datum',
            'error.acceptTerms': 'Morate prihvatiti Uslove Korišćenja i Politiku Privatnosti da biste se registrovali',
    
            // Dashboard
            'dashboard.currentMonthTotal': 'Ukupno za Tekući Mesec',
            'dashboard.netIncome': 'Neto Prihod',
            'dashboard.totalIncome': 'Ukupan Prihod',
            'dashboard.totalExpenses': 'Ukupni Rashodi',
            'dashboard.monthComparison': 'Poređenje Meseci',
            'dashboard.last6Months': 'Poslednjih 6 Meseci',
            'dashboard.recentExpenses': 'Nedavni Rashodi',
            'dashboard.recentIncome': 'Nedavni Prihodi',
            'dashboard.monthlyTotals': 'Mesečni Ukupni',
            'dashboard.noExpenses': 'Još nema rashoda',
            'dashboard.noIncome': 'Još nema prihoda',
            'dashboard.noMonthlyData': 'Još nema mesečnih podataka',
            'dashboard.error': 'Greška',
            'dashboard.tapForDetails': 'Kliknite za pregled po kategorijama',
            'dashboard.categoryBreakdown': 'Pregled po Kategorijama',
            'dashboard.categoryDetails': 'Detalji Kategorija',
            'dashboard.tap': 'Klikni',
            'dashboard.total': 'Ukupno',
            'dashboard.noData': 'Nema podataka',
    
    // Receipt Scanning
            'receipt.scanReceipt': 'Skeniraj Račun',
            'receipt.reviewReceipt': 'Pregled Računa',
            'receipt.processing': 'Obrada računa...',
            'receipt.reviewData': 'Pregled Izvučenih Podataka',
            'receipt.useThisData': 'Koristi Ove Podatke',
            'receipt.retake': 'Ponovo Snimi',
            'receipt.process': 'Obradi',
            'receipt.preview': 'Pregled',
            'receipt.error': 'Greška',
            'receipt.captureError': 'Neuspešno snimanje slike',
            'receipt.processingError': 'Neuspešna obrada računa',
            'receipt.extractionFailed': 'Neuspešno izvlačenje podataka sa računa',
            'receipt.noData': 'Nema izvučenih podataka',
            'receipt.retry': 'Pokušaj Ponovo',
            'receipt.requestingPermission': 'Zahtevanje dozvole za kameru...',
            'receipt.cameraPermissionDenied': 'Dozvola za kameru odbijena. Molimo omogućite je u postavkama.',
            'receipt.requestPermission': 'Zatraži Dozvolu',
            'receipt.galleryPermissionDenied': 'Dozvola za galeriju odbijena. Molimo omogućite je u postavkama.',
            'receipt.galleryError': 'Neuspešno biranje slike iz galerije',
            'receipt.pickFromGallery': 'Izaberi iz Galerije',
            'receipt.selectReceiptPhoto': 'Izaberi Sliku Računa',
            'receipt.webCameraNotSupported': 'Kamera nije podržana na webu. Molimo koristite "Izaberi iz Galerije" da odaberete sliku.',
            'receipt.merchantPlaceholder': 'Ime prodavnice ili trgovca',
            'receipt.descriptionPlaceholder': 'Opcionalni opis',
    
    // Expense Categories
    'category.groceries': 'Namirnice',
    'category.utilities': 'Komunalije',
    'category.transportation': 'Prevoz',
    'category.housing': 'Stanovanje',
    'category.healthcare': 'Zdravstvena Zaštita',
    'category.education': 'Obrazovanje',
    'category.entertainment': 'Zabava',
    'category.diningOut': 'Jelo Napolju',
    'category.clothing': 'Odeća',
    'category.personalCare': 'Lična Nega',
    'category.giftsDonations': 'Pokloni i Donacije',
    'category.travel': 'Putovanja',
    'category.loansDebt': 'Krediti i Otplate Duga',
    'category.bankFees': 'Bankovne Naknade i Prekoračenja',
    'category.insurance': 'Osiguranje',
    'category.taxes': 'Porezi',
    'category.other': 'Ostalo',
    
    // Income Categories
    'category.salary': 'Plata',
    'category.freelance': 'Slobodno Zanimanje',
    'category.investment': 'Investicija',
    'category.gift': 'Poklon',
    'category.bonus': 'Bonus',
    'category.otherIncome': 'Ostalo',
    
    // Placeholders
    'placeholder.amount': '0.00',
    'placeholder.description': 'Opcioni opis',
    
            // Authentication
            'auth.login': 'Prijava',
            'auth.signup': 'Registracija',
            'auth.email': 'Email',
            'auth.emailPlaceholder': 'vas@email.com',
            'auth.username': 'Korisničko Ime (opciono)',
            'auth.usernamePlaceholder': 'korisničko ime',
            'auth.loginIdentifier': 'Email ili Korisničko Ime',
            'auth.loginIdentifierPlaceholder': 'email ili korisničko ime',
            'auth.password': 'Lozinka',
            'auth.passwordPlaceholder': 'Unesite lozinku',
            'auth.name': 'Ime',
            'auth.namePlaceholder': 'Vaše ime',
            'auth.haveAccount': 'Već imate nalog? Prijavite se',
            'auth.noAccount': 'Nemate nalog? Registrujte se',
            'auth.forgotPassword': 'Zaboravili ste lozinku?',
            'auth.resetPassword': 'Resetuj Lozinku',
            'auth.resetPasswordTitle': 'Resetujte Vašu Lozinku',
            'auth.resetPasswordMessage': 'Unesite vašu email adresu i poslaćemo vam uputstva za resetovanje lozinke.',
            'auth.resetPasswordSent': 'Ako nalog postoji sa ovom email adresom, uputstva za resetovanje lozinke su poslata.',
            'auth.backToLogin': 'Nazad na Prijavu',
            'auth.acceptTerms1': 'Prihvatam',
            'auth.termsOfService': 'Uslove Korišćenja',
            'auth.and': 'i',
            'auth.privacyPolicy': 'Politiku Privatnosti',
            'auth.deleteAccount': 'Obriši Nalog',
            'auth.confirmDeleteAccount': 'Da li ste sigurni da želite da obrišete svoj nalog? Ovo će trajno obrisati sve vaše podatke uključujući sve rashode. Ova akcija se ne može poništiti.',
            'auth.failedToDeleteAccount': 'Neuspešno brisanje naloga. Molimo pokušajte ponovo.',
            'auth.error': 'Greška',
            
            // Settings
            'screen.settings': 'Podešavanja',
            'settings.openSettings': 'Otvori Podešavanja',
            'settings.selectLanguage': 'Izaberi Jezik',
            'settings.accountInfo': 'Informacije o Nalogu',
            'settings.name': 'Ime',
            'settings.email': 'Email',
            'settings.username': 'Korisničko Ime',
            'settings.changePassword': 'Promeni Lozinku',
            'settings.currentPassword': 'Trenutna Lozinka',
            'settings.currentPasswordPlaceholder': 'Unesite trenutnu lozinku',
            'settings.newPassword': 'Nova Lozinka',
            'settings.newPasswordPlaceholder': 'Unesite novu lozinku',
            'settings.confirmPassword': 'Potvrdite Novu Lozinku',
            'settings.confirmPasswordPlaceholder': 'Potvrdite novu lozinku',
            'settings.passwordChanged': 'Lozinka je uspešno promenjena',
            'settings.failedToChangePassword': 'Neuspešna promena lozinke',
            'settings.invalidCurrentPassword': 'Trenutna lozinka nije tačna',
            'settings.passwordTooShort': 'Lozinka mora imati najmanje 6 karaktera',
            'settings.passwordsDoNotMatch': 'Nove lozinke se ne poklapaju',
            'settings.newPasswordSame': 'Nova lozinka mora biti drugačija od trenutne',
            'settings.fillAllFields': 'Molimo popunite sva polja',
            'settings.networkError': 'Ne može se povezati sa backend-om. Proverite da li je backend pokrenut.',
            'settings.dangerZone': 'Opasna Zona',
            'settings.deleteAccountWarning': 'Kada obrišete svoj nalog, nema povratka. Molimo budite sigurni.',
  },
  es: {
            // Screen titles
            'screen.addExpense': 'Agregar Gasto',
            'screen.editExpense': 'Editar Gasto',
            'screen.addIncome': 'Agregar Ingreso',
            'screen.editIncome': 'Editar Ingreso',
            'screen.scanReceipt': 'Escanear Recibo',
            'screen.reviewReceipt': 'Revisar Recibo',
            'screen.dashboard': 'Panel de Control',
            'screen.categoryBreakdown': 'Desglose por Categoría',
    
    // Labels
    'label.amount': 'Cantidad',
    'label.date': 'Fecha',
    'label.merchant': 'Comerciante',
    'label.category': 'Categoría',
    'label.description': 'Descripción',
    
            // Buttons
            'button.submit': 'Enviar',
            'button.saveChanges': 'Guardar cambios',
            'button.addExpense': 'Agregar Gasto',
            'button.addIncome': 'Agregar Ingreso',
            'button.scanReceipt': 'Escanear recibo (próximamente)',
            'button.ok': 'OK',
            'button.selectCategory': 'Seleccionar una categoría',
            'button.deleteExpense': 'Eliminar Gasto',
            'button.deleteIncome': 'Eliminar Ingreso',
            'button.delete': 'Eliminar',
            'button.cancel': 'Cancelar',
            'button.overview': 'Resumen',
            'button.income': 'Ingresos',
            'button.expenses': 'Gastos',
    
            // Messages
            'message.expenseAdded': '¡Gasto agregado exitosamente!',
            'message.expenseUpdated': 'Gasto actualizado',
            'message.expenseDeleted': 'Gasto eliminado exitosamente',
            'message.deletingExpense': 'Eliminando gasto...',
            'message.confirmDelete': '¿Está seguro de que desea eliminar este gasto? Esta acción no se puede deshacer.',
            'message.confirmDeleteIncome': '¿Está seguro de que desea eliminar este ingreso? Esta acción no se puede deshacer.',
            'message.incomeAdded': '¡Ingreso agregado exitosamente!',
            'message.incomeUpdated': 'Ingreso actualizado',
            'message.incomeDeleted': 'Ingreso eliminado exitosamente',
            'message.deletingIncome': 'Eliminando ingreso...',
            'message.success': 'Éxito',
            'message.loadingExpense': 'Cargando gasto...',
            'message.loadingIncome': 'Cargando ingreso...',
            'message.failedToCreate': 'Error al crear gasto',
            'message.failedToUpdate': 'Error al actualizar gasto',
            'message.failedToDelete': 'Error al eliminar gasto',
            'message.failedToLoad': 'Error al cargar gasto',
            'message.failedToCreateIncome': 'Error al crear ingreso',
            'message.failedToUpdateIncome': 'Error al actualizar ingreso',
            'message.failedToDeleteIncome': 'Error al eliminar ingreso',
            'message.failedToLoadIncome': 'Error al cargar ingreso',
    
    // Validation errors
            'error.invalidAmount': 'Por favor ingrese una cantidad válida mayor que 0',
            'error.selectCategory': 'Por favor seleccione una categoría',
            'error.selectDate': 'Por favor seleccione una fecha',
            'error.acceptTerms': 'Debe aceptar los Términos de Servicio y la Política de Privacidad para registrarse',
    
            // Dashboard
            'dashboard.currentMonthTotal': 'Total del Mes Actual',
            'dashboard.netIncome': 'Ingreso Neto',
            'dashboard.totalIncome': 'Ingreso Total',
            'dashboard.totalExpenses': 'Gastos Totales',
            'dashboard.monthComparison': 'Comparación Mensual',
            'dashboard.last6Months': 'Últimos 6 Meses',
            'dashboard.recentExpenses': 'Gastos Recientes',
            'dashboard.recentIncome': 'Ingresos Recientes',
            'dashboard.monthlyTotals': 'Totales Mensuales',
            'dashboard.noExpenses': 'Aún no hay gastos',
            'dashboard.noIncome': 'Aún no hay ingresos',
            'dashboard.noMonthlyData': 'Aún no hay datos mensuales',
            'dashboard.error': 'Error',
            'dashboard.tapForDetails': 'Toca para ver el desglose por categoría',
            'dashboard.categoryBreakdown': 'Desglose por Categoría',
            'dashboard.categoryDetails': 'Detalles de Categoría',
            'dashboard.tap': 'Toca',
            'dashboard.total': 'Total',
            'dashboard.noData': 'Sin datos',
    
    // Receipt Scanning
            'receipt.scanReceipt': 'Escanear Recibo',
            'receipt.reviewReceipt': 'Revisar Recibo',
            'receipt.processing': 'Procesando recibo...',
            'receipt.reviewData': 'Revisar Datos Extraídos',
            'receipt.useThisData': 'Usar Estos Datos',
            'receipt.retake': 'Volver a Tomar',
            'receipt.process': 'Procesar',
            'receipt.preview': 'Vista Previa',
            'receipt.error': 'Error',
            'receipt.captureError': 'Error al capturar imagen',
            'receipt.processingError': 'Error al procesar recibo',
            'receipt.extractionFailed': 'Error al extraer datos del recibo',
            'receipt.noData': 'No se extrajeron datos',
            'receipt.retry': 'Reintentar',
            'receipt.requestingPermission': 'Solicitando permiso de cámara...',
            'receipt.cameraPermissionDenied': 'Permiso de cámara denegado. Por favor, habilítelo en la configuración.',
            'receipt.requestPermission': 'Solicitar Permiso',
            'receipt.galleryPermissionDenied': 'Permiso de galería denegado. Por favor, habilítelo en la configuración.',
            'receipt.galleryError': 'Error al seleccionar imagen de la galería',
            'receipt.pickFromGallery': 'Elegir de la Galería',
            'receipt.selectReceiptPhoto': 'Seleccionar Foto del Recibo',
            'receipt.webCameraNotSupported': 'La cámara no es compatible en la web. Por favor use "Elegir de la Galería" para seleccionar una imagen.',
            'receipt.merchantPlaceholder': 'Nombre de la tienda o comerciante',
            'receipt.descriptionPlaceholder': 'Descripción opcional',
    
    // Expense Categories
    'category.groceries': 'Comestibles',
    'category.utilities': 'Servicios Públicos',
    'category.transportation': 'Transporte',
    'category.housing': 'Vivienda',
    'category.healthcare': 'Atención Médica',
    'category.education': 'Educación',
    'category.entertainment': 'Entretenimiento',
    'category.diningOut': 'Comer Fuera',
    'category.clothing': 'Ropa',
    'category.personalCare': 'Cuidado Personal',
    'category.giftsDonations': 'Regalos y Donaciones',
    'category.travel': 'Viajes',
    'category.loansDebt': 'Préstamos y Pagos de Deuda',
    'category.bankFees': 'Tarifas Bancarias y Sobregiros',
    'category.insurance': 'Seguro',
    'category.taxes': 'Impuestos',
    'category.other': 'Otro',
    
    // Income Categories
    'category.salary': 'Salario',
    'category.freelance': 'Trabajo Independiente',
    'category.investment': 'Inversión',
    'category.gift': 'Regalo',
    'category.bonus': 'Bono',
    'category.otherIncome': 'Otro',
    
    // Placeholders
    'placeholder.amount': '0.00',
    'placeholder.description': 'Descripción opcional',
    
            // Authentication
            'auth.login': 'Iniciar Sesión',
            'auth.signup': 'Registrarse',
            'auth.email': 'Correo Electrónico',
            'auth.emailPlaceholder': 'tu@email.com',
            'auth.username': 'Nombre de Usuario (opcional)',
            'auth.usernamePlaceholder': 'nombre de usuario',
            'auth.loginIdentifier': 'Correo Electrónico o Nombre de Usuario',
            'auth.loginIdentifierPlaceholder': 'correo electrónico o nombre de usuario',
            'auth.password': 'Contraseña',
            'auth.passwordPlaceholder': 'Ingrese la contraseña',
            'auth.name': 'Nombre',
            'auth.namePlaceholder': 'Tu nombre',
            'auth.haveAccount': '¿Ya tienes una cuenta? Inicia sesión',
            'auth.noAccount': '¿No tienes una cuenta? Regístrate',
            'auth.forgotPassword': '¿Olvidaste tu contraseña?',
            'auth.resetPassword': 'Restablecer Contraseña',
            'auth.resetPasswordTitle': 'Restablece Tu Contraseña',
            'auth.resetPasswordMessage': 'Ingresa tu dirección de correo electrónico y te enviaremos instrucciones para restablecer tu contraseña.',
            'auth.resetPasswordSent': 'Si existe una cuenta con este correo electrónico, se han enviado instrucciones para restablecer la contraseña.',
            'auth.backToLogin': 'Volver a Iniciar Sesión',
            'auth.acceptTerms1': 'Acepto los',
            'auth.termsOfService': 'Términos de Servicio',
            'auth.and': 'y',
            'auth.privacyPolicy': 'Política de Privacidad',
            'auth.deleteAccount': 'Eliminar Cuenta',
            'auth.confirmDeleteAccount': '¿Está seguro de que desea eliminar su cuenta? Esto eliminará permanentemente todos sus datos, incluidos todos los gastos. Esta acción no se puede deshacer.',
            'auth.failedToDeleteAccount': 'Error al eliminar la cuenta. Por favor, inténtelo de nuevo.',
            'auth.error': 'Error',
            
            // Settings
            'screen.settings': 'Configuración',
            'settings.openSettings': 'Abrir Configuración',
            'settings.selectLanguage': 'Seleccionar Idioma',
            'settings.accountInfo': 'Información de la Cuenta',
            'settings.name': 'Nombre',
            'settings.email': 'Correo Electrónico',
            'settings.username': 'Nombre de Usuario',
            'settings.changePassword': 'Cambiar Contraseña',
            'settings.currentPassword': 'Contraseña Actual',
            'settings.currentPasswordPlaceholder': 'Ingrese la contraseña actual',
            'settings.newPassword': 'Nueva Contraseña',
            'settings.newPasswordPlaceholder': 'Ingrese la nueva contraseña',
            'settings.confirmPassword': 'Confirmar Nueva Contraseña',
            'settings.confirmPasswordPlaceholder': 'Confirme la nueva contraseña',
            'settings.passwordChanged': 'Contraseña cambiada exitosamente',
            'settings.failedToChangePassword': 'Error al cambiar la contraseña',
            'settings.invalidCurrentPassword': 'La contraseña actual es incorrecta',
            'settings.passwordTooShort': 'La contraseña debe tener al menos 6 caracteres',
            'settings.passwordsDoNotMatch': 'Las nuevas contraseñas no coinciden',
            'settings.newPasswordSame': 'La nueva contraseña debe ser diferente de la contraseña actual',
            'settings.fillAllFields': 'Por favor complete todos los campos',
            'settings.networkError': 'No se puede conectar al servidor. Asegúrese de que el servidor esté en ejecución.',
            'settings.dangerZone': 'Zona de Peligro',
            'settings.deleteAccountWarning': 'Una vez que elimine su cuenta, no hay vuelta atrás. Por favor, tenga cuidado.',
  },
  pt: {
            'screen.addExpense': 'Adicionar Despesa',
            'screen.editExpense': 'Editar Despesa',
            'screen.addIncome': 'Adicionar Receita',
            'screen.editIncome': 'Editar Receita',
            'screen.scanReceipt': 'Escanear Recibo',
            'screen.reviewReceipt': 'Revisar Recibo',
            'screen.dashboard': 'Painel de Controle',
            'screen.categoryBreakdown': 'Detalhamento por Categoria',
            'label.amount': 'Valor',
            'label.date': 'Data',
            'label.merchant': 'Comerciante',
            'label.category': 'Categoria',
            'label.description': 'Descrição',
            'button.submit': 'Enviar',
            'button.saveChanges': 'Salvar alterações',
            'button.addExpense': 'Adicionar Despesa',
            'button.addIncome': 'Adicionar Receita',
            'button.scanReceipt': 'Escanear recibo (em breve)',
            'button.ok': 'OK',
            'button.selectCategory': 'Selecionar uma categoria',
            'button.deleteExpense': 'Excluir Despesa',
            'button.deleteIncome': 'Excluir Receita',
            'button.delete': 'Excluir',
            'button.cancel': 'Cancelar',
            'button.overview': 'Visão Geral',
            'button.income': 'Receitas',
            'button.expenses': 'Despesas',
            'message.expenseAdded': 'Despesa adicionada com sucesso!',
            'message.expenseUpdated': 'Despesa atualizada',
            'message.expenseDeleted': 'Despesa excluída com sucesso',
            'message.deletingExpense': 'Excluindo despesa...',
            'message.confirmDelete': 'Tem certeza de que deseja excluir esta despesa? Esta ação não pode ser desfeita.',
            'message.confirmDeleteIncome': 'Tem certeza de que deseja excluir esta receita? Esta ação não pode ser desfeita.',
            'message.incomeAdded': 'Receita adicionada com sucesso!',
            'message.incomeUpdated': 'Receita atualizada',
            'message.incomeDeleted': 'Receita excluída com sucesso',
            'message.deletingIncome': 'Excluindo receita...',
            'message.success': 'Sucesso',
            'message.loadingExpense': 'Carregando despesa...',
            'message.loadingIncome': 'Carregando receita...',
            'message.failedToCreate': 'Falha ao criar despesa',
            'message.failedToUpdate': 'Falha ao atualizar despesa',
            'message.failedToDelete': 'Falha ao excluir despesa',
            'message.failedToLoad': 'Falha ao carregar despesa',
            'message.failedToCreateIncome': 'Falha ao criar receita',
            'message.failedToUpdateIncome': 'Falha ao atualizar receita',
            'message.failedToDeleteIncome': 'Falha ao excluir receita',
            'message.failedToLoadIncome': 'Falha ao carregar receita',
            'error.invalidAmount': 'Por favor, insira um valor válido maior que 0',
            'error.selectCategory': 'Por favor, selecione uma categoria',
            'error.selectDate': 'Por favor, selecione uma data',
            'error.acceptTerms': 'Você deve aceitar os Termos de Serviço e a Política de Privacidade para se registrar',
            'dashboard.currentMonthTotal': 'Total do Mês Atual',
            'dashboard.netIncome': 'Receita Líquida',
            'dashboard.totalIncome': 'Receita Total',
            'dashboard.totalExpenses': 'Despesas Totais',
            'dashboard.monthComparison': 'Comparação Mensal',
            'dashboard.last6Months': 'Últimos 6 Meses',
            'dashboard.recentExpenses': 'Despesas Recentes',
            'dashboard.recentIncome': 'Receitas Recentes',
            'dashboard.monthlyTotals': 'Totais Mensais',
            'dashboard.noExpenses': 'Ainda não há despesas',
            'dashboard.noIncome': 'Ainda não há receitas',
            'dashboard.noMonthlyData': 'Ainda não há dados mensais',
            'dashboard.error': 'Erro',
            'dashboard.tapForDetails': 'Toque para ver o detalhamento por categoria',
            'dashboard.categoryBreakdown': 'Detalhamento por Categoria',
            'dashboard.categoryDetails': 'Detalhes da Categoria',
            'dashboard.tap': 'Toque',
            'dashboard.total': 'Total',
            'dashboard.noData': 'Sem dados',
            'receipt.scanReceipt': 'Escanear Recibo',
            'receipt.reviewReceipt': 'Revisar Recibo',
            'receipt.processing': 'Processando recibo...',
            'receipt.reviewData': 'Revisar Dados Extraídos',
            'receipt.useThisData': 'Usar Estes Dados',
            'receipt.retake': 'Tirar Novamente',
            'receipt.process': 'Processar',
            'receipt.preview': 'Visualização',
            'receipt.error': 'Erro',
            'receipt.captureError': 'Falha ao capturar imagem',
            'receipt.processingError': 'Falha ao processar recibo',
            'receipt.extractionFailed': 'Falha ao extrair dados do recibo',
            'receipt.noData': 'Nenhum dado extraído',
            'receipt.retry': 'Tentar Novamente',
            'receipt.requestingPermission': 'Solicitando permissão da câmera...',
            'receipt.cameraPermissionDenied': 'Permissão da câmera negada. Por favor, habilite nas configurações.',
            'receipt.requestPermission': 'Solicitar Permissão',
            'receipt.galleryPermissionDenied': 'Permissão da galeria negada. Por favor, habilite nas configurações.',
            'receipt.galleryError': 'Falha ao selecionar imagem da galeria',
            'receipt.pickFromGallery': 'Escolher da Galeria',
            'receipt.selectReceiptPhoto': 'Selecionar Foto do Recibo',
            'receipt.webCameraNotSupported': 'A câmera não é suportada na web. Por favor, use "Escolher da Galeria" para selecionar uma imagem.',
            'receipt.merchantPlaceholder': 'Nome da loja ou comerciante',
            'receipt.descriptionPlaceholder': 'Descrição opcional',
            'category.groceries': 'Mantimentos',
            'category.utilities': 'Utilidades',
            'category.transportation': 'Transporte',
            'category.housing': 'Moradia',
            'category.healthcare': 'Cuidados de Saúde',
            'category.education': 'Educação',
            'category.entertainment': 'Entretenimento',
            'category.diningOut': 'Comer Fora',
            'category.clothing': 'Roupas',
            'category.personalCare': 'Cuidados Pessoais',
            'category.giftsDonations': 'Presentes e Doações',
            'category.travel': 'Viagens',
            'category.loansDebt': 'Empréstimos e Pagamentos de Dívidas',
            'category.bankFees': 'Taxas Bancárias e Estouros',
            'category.insurance': 'Seguro',
            'category.taxes': 'Impostos',
            'category.other': 'Outro',
            'category.salary': 'Salário',
            'category.freelance': 'Freelance',
            'category.investment': 'Investimento',
            'category.gift': 'Presente',
            'category.bonus': 'Bônus',
            'category.otherIncome': 'Outro',
            'placeholder.amount': '0.00',
            'placeholder.description': 'Descrição opcional',
            'auth.login': 'Entrar',
            'auth.signup': 'Cadastrar',
            'auth.email': 'E-mail',
            'auth.emailPlaceholder': 'seu@email.com',
            'auth.username': 'Nome de Usuário (opcional)',
            'auth.usernamePlaceholder': 'nome de usuário',
            'auth.loginIdentifier': 'E-mail ou Nome de Usuário',
            'auth.loginIdentifierPlaceholder': 'e-mail ou nome de usuário',
            'auth.password': 'Senha',
            'auth.passwordPlaceholder': 'Digite a senha',
            'auth.name': 'Nome',
            'auth.namePlaceholder': 'Seu nome',
            'auth.haveAccount': 'Já tem uma conta? Entrar',
            'auth.noAccount': 'Não tem uma conta? Cadastrar',
            'auth.forgotPassword': 'Esqueceu a senha?',
            'auth.resetPassword': 'Redefinir Senha',
            'auth.resetPasswordTitle': 'Redefina Sua Senha',
            'auth.resetPasswordMessage': 'Digite seu endereço de e-mail e enviaremos instruções para redefinir sua senha.',
            'auth.resetPasswordSent': 'Se existir uma conta com este e-mail, instruções para redefinir a senha foram enviadas.',
            'auth.backToLogin': 'Voltar para Entrar',
            'auth.acceptTerms1': 'Eu concordo com os',
            'auth.termsOfService': 'Termos de Serviço',
            'auth.and': 'e',
            'auth.privacyPolicy': 'Política de Privacidade',
            'auth.deleteAccount': 'Excluir Conta',
            'auth.confirmDeleteAccount': 'Tem certeza de que deseja excluir sua conta? Isso excluirá permanentemente todos os seus dados, incluindo todas as despesas. Esta ação não pode ser desfeita.',
            'auth.failedToDeleteAccount': 'Falha ao excluir a conta. Por favor, tente novamente.',
            'auth.error': 'Erro',
            'screen.settings': 'Configurações',
            'settings.openSettings': 'Abrir Configurações',
            'settings.selectLanguage': 'Selecionar Idioma',
            'settings.accountInfo': 'Informações da Conta',
            'settings.name': 'Nome',
            'settings.email': 'E-mail',
            'settings.username': 'Nome de Usuário',
            'settings.changePassword': 'Alterar Senha',
            'settings.currentPassword': 'Senha Atual',
            'settings.currentPasswordPlaceholder': 'Digite a senha atual',
            'settings.newPassword': 'Nova Senha',
            'settings.newPasswordPlaceholder': 'Digite a nova senha',
            'settings.confirmPassword': 'Confirmar Nova Senha',
            'settings.confirmPasswordPlaceholder': 'Confirme a nova senha',
            'settings.passwordChanged': 'Senha alterada com sucesso',
            'settings.failedToChangePassword': 'Falha ao alterar a senha',
            'settings.invalidCurrentPassword': 'A senha atual está incorreta',
            'settings.passwordTooShort': 'A senha deve ter pelo menos 6 caracteres',
            'settings.passwordsDoNotMatch': 'As novas senhas não coincidem',
            'settings.newPasswordSame': 'A nova senha deve ser diferente da senha atual',
            'settings.fillAllFields': 'Por favor, preencha todos os campos',
            'settings.networkError': 'Não é possível conectar ao servidor. Certifique-se de que o servidor está em execução.',
            'settings.dangerZone': 'Zona de Perigo',
            'settings.deleteAccountWarning': 'Depois de excluir sua conta, não há como voltar atrás. Por favor, tenha certeza.',
  },
  fr: {
            'screen.addExpense': 'Ajouter une Dépense',
            'screen.editExpense': 'Modifier la Dépense',
            'screen.addIncome': 'Ajouter un Revenu',
            'screen.editIncome': 'Modifier le Revenu',
            'screen.scanReceipt': 'Scanner le Reçu',
            'screen.reviewReceipt': 'Examiner le Reçu',
            'screen.dashboard': 'Tableau de Bord',
            'screen.categoryBreakdown': 'Répartition par Catégorie',
            'label.amount': 'Montant',
            'label.date': 'Date',
            'label.merchant': 'Commerçant',
            'label.category': 'Catégorie',
            'label.description': 'Description',
            'button.submit': 'Envoyer',
            'button.saveChanges': 'Enregistrer les modifications',
            'button.addExpense': 'Ajouter une Dépense',
            'button.addIncome': 'Ajouter un Revenu',
            'button.scanReceipt': 'Scanner le reçu (bientôt disponible)',
            'button.ok': 'OK',
            'button.selectCategory': 'Sélectionner une catégorie',
            'button.deleteExpense': 'Supprimer la Dépense',
            'button.deleteIncome': 'Supprimer le Revenu',
            'button.delete': 'Supprimer',
            'button.cancel': 'Annuler',
            'button.overview': 'Aperçu',
            'button.income': 'Revenus',
            'button.expenses': 'Dépenses',
            'message.expenseAdded': 'Dépense ajoutée avec succès !',
            'message.expenseUpdated': 'Dépense mise à jour',
            'message.expenseDeleted': 'Dépense supprimée avec succès',
            'message.deletingExpense': 'Suppression de la dépense...',
            'message.confirmDelete': 'Êtes-vous sûr de vouloir supprimer cette dépense ? Cette action ne peut pas être annulée.',
            'message.confirmDeleteIncome': 'Êtes-vous sûr de vouloir supprimer ce revenu ? Cette action ne peut pas être annulée.',
            'message.incomeAdded': 'Revenu ajouté avec succès !',
            'message.incomeUpdated': 'Revenu mis à jour',
            'message.incomeDeleted': 'Revenu supprimé avec succès',
            'message.deletingIncome': 'Suppression du revenu...',
            'message.success': 'Succès',
            'message.loadingExpense': 'Chargement de la dépense...',
            'message.loadingIncome': 'Chargement du revenu...',
            'message.failedToCreate': 'Échec de la création de la dépense',
            'message.failedToUpdate': 'Échec de la mise à jour de la dépense',
            'message.failedToDelete': 'Échec de la suppression de la dépense',
            'message.failedToLoad': 'Échec du chargement de la dépense',
            'message.failedToCreateIncome': 'Échec de la création du revenu',
            'message.failedToUpdateIncome': 'Échec de la mise à jour du revenu',
            'message.failedToDeleteIncome': 'Échec de la suppression du revenu',
            'message.failedToLoadIncome': 'Échec du chargement du revenu',
            'error.invalidAmount': 'Veuillez entrer un montant valide supérieur à 0',
            'error.selectCategory': 'Veuillez sélectionner une catégorie',
            'error.selectDate': 'Veuillez sélectionner une date',
            'error.acceptTerms': 'Vous devez accepter les Conditions d\'utilisation et la Politique de confidentialité pour vous inscrire',
            'dashboard.currentMonthTotal': 'Total du Mois en Cours',
            'dashboard.netIncome': 'Revenu Net',
            'dashboard.totalIncome': 'Revenu Total',
            'dashboard.totalExpenses': 'Dépenses Totales',
            'dashboard.monthComparison': 'Comparaison Mensuelle',
            'dashboard.last6Months': '6 Derniers Mois',
            'dashboard.recentExpenses': 'Dépenses Récentes',
            'dashboard.recentIncome': 'Revenus Récents',
            'dashboard.monthlyTotals': 'Totaux Mensuels',
            'dashboard.noExpenses': 'Aucune dépense pour le moment',
            'dashboard.noIncome': 'Aucun revenu pour le moment',
            'dashboard.noMonthlyData': 'Aucune donnée mensuelle pour le moment',
            'dashboard.error': 'Erreur',
            'dashboard.tapForDetails': 'Appuyez pour voir la répartition par catégorie',
            'dashboard.categoryBreakdown': 'Répartition par Catégorie',
            'dashboard.categoryDetails': 'Détails de la Catégorie',
            'dashboard.tap': 'Appuyez',
            'dashboard.total': 'Total',
            'dashboard.noData': 'Aucune donnée',
            'receipt.scanReceipt': 'Scanner le Reçu',
            'receipt.reviewReceipt': 'Examiner le Reçu',
            'receipt.processing': 'Traitement du reçu...',
            'receipt.reviewData': 'Examiner les Données Extraites',
            'receipt.useThisData': 'Utiliser Ces Données',
            'receipt.retake': 'Reprendre',
            'receipt.process': 'Traiter',
            'receipt.preview': 'Aperçu',
            'receipt.error': 'Erreur',
            'receipt.captureError': 'Échec de la capture d\'image',
            'receipt.processingError': 'Échec du traitement du reçu',
            'receipt.extractionFailed': 'Échec de l\'extraction des données du reçu',
            'receipt.noData': 'Aucune donnée extraite',
            'receipt.retry': 'Réessayer',
            'receipt.requestingPermission': 'Demande d\'autorisation de la caméra...',
            'receipt.cameraPermissionDenied': 'Autorisation de la caméra refusée. Veuillez l\'activer dans les paramètres.',
            'receipt.requestPermission': 'Demander l\'Autorisation',
            'receipt.galleryPermissionDenied': 'Autorisation de la galerie refusée. Veuillez l\'activer dans les paramètres.',
            'receipt.galleryError': 'Échec de la sélection d\'image dans la galerie',
            'receipt.pickFromGallery': 'Choisir dans la Galerie',
            'receipt.selectReceiptPhoto': 'Sélectionner la Photo du Reçu',
            'receipt.webCameraNotSupported': 'La caméra n\'est pas prise en charge sur le web. Veuillez utiliser "Choisir dans la Galerie" pour sélectionner une image.',
            'receipt.merchantPlaceholder': 'Nom du magasin ou du commerçant',
            'receipt.descriptionPlaceholder': 'Description optionnelle',
            'category.groceries': 'Épicerie',
            'category.utilities': 'Services Publics',
            'category.transportation': 'Transport',
            'category.housing': 'Logement',
            'category.healthcare': 'Soins de Santé',
            'category.education': 'Éducation',
            'category.entertainment': 'Divertissement',
            'category.diningOut': 'Sortie au Restaurant',
            'category.clothing': 'Vêtements',
            'category.personalCare': 'Soins Personnels',
            'category.giftsDonations': 'Cadeaux et Dons',
            'category.travel': 'Voyages',
            'category.loansDebt': 'Prêts et Remboursements de Dettes',
            'category.bankFees': 'Frais Bancaires et Découverts',
            'category.insurance': 'Assurance',
            'category.taxes': 'Impôts',
            'category.other': 'Autre',
            'category.salary': 'Salaire',
            'category.freelance': 'Freelance',
            'category.investment': 'Investissement',
            'category.gift': 'Cadeau',
            'category.bonus': 'Prime',
            'category.otherIncome': 'Autre',
            'placeholder.amount': '0.00',
            'placeholder.description': 'Description optionnelle',
            'auth.login': 'Se Connecter',
            'auth.signup': 'S\'inscrire',
            'auth.email': 'E-mail',
            'auth.emailPlaceholder': 'votre@email.com',
            'auth.username': 'Nom d\'utilisateur (optionnel)',
            'auth.usernamePlaceholder': 'nom d\'utilisateur',
            'auth.loginIdentifier': 'E-mail ou Nom d\'utilisateur',
            'auth.loginIdentifierPlaceholder': 'e-mail ou nom d\'utilisateur',
            'auth.password': 'Mot de passe',
            'auth.passwordPlaceholder': 'Entrez le mot de passe',
            'auth.name': 'Nom',
            'auth.namePlaceholder': 'Votre nom',
            'auth.haveAccount': 'Vous avez déjà un compte ? Se connecter',
            'auth.noAccount': 'Vous n\'avez pas de compte ? S\'inscrire',
            'auth.forgotPassword': 'Mot de passe oublié ?',
            'auth.resetPassword': 'Réinitialiser le Mot de passe',
            'auth.resetPasswordTitle': 'Réinitialisez Votre Mot de passe',
            'auth.resetPasswordMessage': 'Entrez votre adresse e-mail et nous vous enverrons des instructions pour réinitialiser votre mot de passe.',
            'auth.resetPasswordSent': 'Si un compte existe avec cet e-mail, des instructions pour réinitialiser le mot de passe ont été envoyées.',
            'auth.backToLogin': 'Retour à la Connexion',
            'auth.acceptTerms1': 'J\'accepte les',
            'auth.termsOfService': 'Conditions d\'utilisation',
            'auth.and': 'et',
            'auth.privacyPolicy': 'Politique de Confidentialité',
            'auth.deleteAccount': 'Supprimer le Compte',
            'auth.confirmDeleteAccount': 'Êtes-vous sûr de vouloir supprimer votre compte ? Cela supprimera définitivement toutes vos données, y compris toutes les dépenses. Cette action ne peut pas être annulée.',
            'auth.failedToDeleteAccount': 'Échec de la suppression du compte. Veuillez réessayer.',
            'auth.error': 'Erreur',
            'screen.settings': 'Paramètres',
            'settings.openSettings': 'Ouvrir les Paramètres',
            'settings.selectLanguage': 'Sélectionner la Langue',
            'settings.accountInfo': 'Informations du Compte',
            'settings.name': 'Nom',
            'settings.email': 'E-mail',
            'settings.username': 'Nom d\'utilisateur',
            'settings.changePassword': 'Changer le Mot de passe',
            'settings.currentPassword': 'Mot de passe Actuel',
            'settings.currentPasswordPlaceholder': 'Entrez le mot de passe actuel',
            'settings.newPassword': 'Nouveau Mot de passe',
            'settings.newPasswordPlaceholder': 'Entrez le nouveau mot de passe',
            'settings.confirmPassword': 'Confirmer le Nouveau Mot de passe',
            'settings.confirmPasswordPlaceholder': 'Confirmez le nouveau mot de passe',
            'settings.passwordChanged': 'Mot de passe modifié avec succès',
            'settings.failedToChangePassword': 'Échec de la modification du mot de passe',
            'settings.invalidCurrentPassword': 'Le mot de passe actuel est incorrect',
            'settings.passwordTooShort': 'Le mot de passe doit contenir au moins 6 caractères',
            'settings.passwordsDoNotMatch': 'Les nouveaux mots de passe ne correspondent pas',
            'settings.newPasswordSame': 'Le nouveau mot de passe doit être différent du mot de passe actuel',
            'settings.fillAllFields': 'Veuillez remplir tous les champs',
            'settings.networkError': 'Impossible de se connecter au serveur. Assurez-vous que le serveur est en cours d\'exécution.',
            'settings.dangerZone': 'Zone de Danger',
            'settings.deleteAccountWarning': 'Une fois que vous supprimez votre compte, il n\'y a pas de retour en arrière. Veuillez être certain.',
  },
  de: {
            'screen.addExpense': 'Ausgabe Hinzufügen',
            'screen.editExpense': 'Ausgabe Bearbeiten',
            'screen.addIncome': 'Einnahme Hinzufügen',
            'screen.editIncome': 'Einnahme Bearbeiten',
            'screen.scanReceipt': 'Beleg Scannen',
            'screen.reviewReceipt': 'Beleg Überprüfen',
            'screen.dashboard': 'Dashboard',
            'screen.categoryBreakdown': 'Aufschlüsselung nach Kategorie',
            'label.amount': 'Betrag',
            'label.date': 'Datum',
            'label.merchant': 'Händler',
            'label.category': 'Kategorie',
            'label.description': 'Beschreibung',
            'button.submit': 'Senden',
            'button.saveChanges': 'Änderungen speichern',
            'button.addExpense': 'Ausgabe Hinzufügen',
            'button.addIncome': 'Einnahme Hinzufügen',
            'button.scanReceipt': 'Beleg scannen (demnächst)',
            'button.ok': 'OK',
            'button.selectCategory': 'Kategorie auswählen',
            'button.deleteExpense': 'Ausgabe Löschen',
            'button.deleteIncome': 'Einnahme Löschen',
            'button.delete': 'Löschen',
            'button.cancel': 'Abbrechen',
            'button.overview': 'Übersicht',
            'button.income': 'Einnahmen',
            'button.expenses': 'Ausgaben',
            'message.expenseAdded': 'Ausgabe erfolgreich hinzugefügt!',
            'message.expenseUpdated': 'Ausgabe aktualisiert',
            'message.expenseDeleted': 'Ausgabe erfolgreich gelöscht',
            'message.deletingExpense': 'Ausgabe wird gelöscht...',
            'message.confirmDelete': 'Sind Sie sicher, dass Sie diese Ausgabe löschen möchten? Diese Aktion kann nicht rückgängig gemacht werden.',
            'message.confirmDeleteIncome': 'Sind Sie sicher, dass Sie diese Einnahme löschen möchten? Diese Aktion kann nicht rückgängig gemacht werden.',
            'message.incomeAdded': 'Einnahme erfolgreich hinzugefügt!',
            'message.incomeUpdated': 'Einnahme aktualisiert',
            'message.incomeDeleted': 'Einnahme erfolgreich gelöscht',
            'message.deletingIncome': 'Einnahme wird gelöscht...',
            'message.success': 'Erfolg',
            'message.loadingExpense': 'Ausgabe wird geladen...',
            'message.loadingIncome': 'Einnahme wird geladen...',
            'message.failedToCreate': 'Fehler beim Erstellen der Ausgabe',
            'message.failedToUpdate': 'Fehler beim Aktualisieren der Ausgabe',
            'message.failedToDelete': 'Fehler beim Löschen der Ausgabe',
            'message.failedToLoad': 'Fehler beim Laden der Ausgabe',
            'message.failedToCreateIncome': 'Fehler beim Erstellen der Einnahme',
            'message.failedToUpdateIncome': 'Fehler beim Aktualisieren der Einnahme',
            'message.failedToDeleteIncome': 'Fehler beim Löschen der Einnahme',
            'message.failedToLoadIncome': 'Fehler beim Laden der Einnahme',
            'error.invalidAmount': 'Bitte geben Sie einen gültigen Betrag größer als 0 ein',
            'error.selectCategory': 'Bitte wählen Sie eine Kategorie',
            'error.selectDate': 'Bitte wählen Sie ein Datum',
            'error.acceptTerms': 'Sie müssen den Nutzungsbedingungen und der Datenschutzerklärung zustimmen, um sich zu registrieren',
            'dashboard.currentMonthTotal': 'Gesamt des Aktuellen Monats',
            'dashboard.netIncome': 'Nettoeinkommen',
            'dashboard.totalIncome': 'Gesamteinnahmen',
            'dashboard.totalExpenses': 'Gesamtausgaben',
            'dashboard.monthComparison': 'Monatsvergleich',
            'dashboard.last6Months': 'Letzte 6 Monate',
            'dashboard.recentExpenses': 'Letzte Ausgaben',
            'dashboard.recentIncome': 'Letzte Einnahmen',
            'dashboard.monthlyTotals': 'Monatliche Summen',
            'dashboard.noExpenses': 'Noch keine Ausgaben',
            'dashboard.noIncome': 'Noch keine Einnahmen',
            'dashboard.noMonthlyData': 'Noch keine monatlichen Daten',
            'dashboard.error': 'Fehler',
            'dashboard.tapForDetails': 'Tippen Sie für die Aufschlüsselung nach Kategorie',
            'dashboard.categoryBreakdown': 'Aufschlüsselung nach Kategorie',
            'dashboard.categoryDetails': 'Kategoriedetails',
            'dashboard.tap': 'Tippen',
            'dashboard.total': 'Gesamt',
            'dashboard.noData': 'Keine Daten',
            'receipt.scanReceipt': 'Beleg Scannen',
            'receipt.reviewReceipt': 'Beleg Überprüfen',
            'receipt.processing': 'Beleg wird verarbeitet...',
            'receipt.reviewData': 'Extrahierte Daten Überprüfen',
            'receipt.useThisData': 'Diese Daten Verwenden',
            'receipt.retake': 'Erneut Aufnehmen',
            'receipt.process': 'Verarbeiten',
            'receipt.preview': 'Vorschau',
            'receipt.error': 'Fehler',
            'receipt.captureError': 'Fehler beim Erfassen des Bildes',
            'receipt.processingError': 'Fehler beim Verarbeiten des Belegs',
            'receipt.extractionFailed': 'Fehler beim Extrahieren der Daten vom Beleg',
            'receipt.noData': 'Keine Daten extrahiert',
            'receipt.retry': 'Wiederholen',
            'receipt.requestingPermission': 'Kamera-Berechtigung wird angefordert...',
            'receipt.cameraPermissionDenied': 'Kamera-Berechtigung verweigert. Bitte aktivieren Sie sie in den Einstellungen.',
            'receipt.requestPermission': 'Berechtigung Anfordern',
            'receipt.galleryPermissionDenied': 'Galerie-Berechtigung verweigert. Bitte aktivieren Sie sie in den Einstellungen.',
            'receipt.galleryError': 'Fehler beim Auswählen des Bildes aus der Galerie',
            'receipt.pickFromGallery': 'Aus Galerie Auswählen',
            'receipt.selectReceiptPhoto': 'Belegfoto Auswählen',
            'receipt.webCameraNotSupported': 'Kamera wird im Web nicht unterstützt. Bitte verwenden Sie "Aus Galerie Auswählen", um ein Bild auszuwählen.',
            'receipt.merchantPlaceholder': 'Name des Geschäfts oder Händlers',
            'receipt.descriptionPlaceholder': 'Optionale Beschreibung',
            'category.groceries': 'Lebensmittel',
            'category.utilities': 'Nebenkosten',
            'category.transportation': 'Transport',
            'category.housing': 'Wohnen',
            'category.healthcare': 'Gesundheitswesen',
            'category.education': 'Bildung',
            'category.entertainment': 'Unterhaltung',
            'category.diningOut': 'Essen Gehen',
            'category.clothing': 'Kleidung',
            'category.personalCare': 'Persönliche Pflege',
            'category.giftsDonations': 'Geschenke und Spenden',
            'category.travel': 'Reisen',
            'category.loansDebt': 'Kredite und Schuldentilgung',
            'category.bankFees': 'Bankgebühren und Überziehungen',
            'category.insurance': 'Versicherung',
            'category.taxes': 'Steuern',
            'category.other': 'Sonstiges',
            'category.salary': 'Gehalt',
            'category.freelance': 'Freiberuflich',
            'category.investment': 'Investition',
            'category.gift': 'Geschenk',
            'category.bonus': 'Bonus',
            'category.otherIncome': 'Sonstiges',
            'placeholder.amount': '0.00',
            'placeholder.description': 'Optionale Beschreibung',
            'auth.login': 'Anmelden',
            'auth.signup': 'Registrieren',
            'auth.email': 'E-Mail',
            'auth.emailPlaceholder': 'ihre@email.com',
            'auth.username': 'Benutzername (optional)',
            'auth.usernamePlaceholder': 'Benutzername',
            'auth.loginIdentifier': 'E-Mail oder Benutzername',
            'auth.loginIdentifierPlaceholder': 'E-Mail oder Benutzername',
            'auth.password': 'Passwort',
            'auth.passwordPlaceholder': 'Passwort eingeben',
            'auth.name': 'Name',
            'auth.namePlaceholder': 'Ihr Name',
            'auth.haveAccount': 'Haben Sie bereits ein Konto? Anmelden',
            'auth.noAccount': 'Haben Sie kein Konto? Registrieren',
            'auth.forgotPassword': 'Passwort vergessen?',
            'auth.resetPassword': 'Passwort Zurücksetzen',
            'auth.resetPasswordTitle': 'Setzen Sie Ihr Passwort Zurück',
            'auth.resetPasswordMessage': 'Geben Sie Ihre E-Mail-Adresse ein und wir senden Ihnen Anweisungen zum Zurücksetzen Ihres Passworts.',
            'auth.resetPasswordSent': 'Wenn ein Konto mit dieser E-Mail existiert, wurden Anweisungen zum Zurücksetzen des Passworts gesendet.',
            'auth.backToLogin': 'Zurück zur Anmeldung',
            'auth.acceptTerms1': 'Ich stimme den',
            'auth.termsOfService': 'Nutzungsbedingungen',
            'auth.and': 'und',
            'auth.privacyPolicy': 'Datenschutzerklärung',
            'auth.deleteAccount': 'Konto Löschen',
            'auth.confirmDeleteAccount': 'Sind Sie sicher, dass Sie Ihr Konto löschen möchten? Dies wird alle Ihre Daten dauerhaft löschen, einschließlich aller Ausgaben. Diese Aktion kann nicht rückgängig gemacht werden.',
            'auth.failedToDeleteAccount': 'Fehler beim Löschen des Kontos. Bitte versuchen Sie es erneut.',
            'auth.error': 'Fehler',
            'screen.settings': 'Einstellungen',
            'settings.openSettings': 'Einstellungen Öffnen',
            'settings.selectLanguage': 'Sprache Auswählen',
            'settings.accountInfo': 'Kontoinformationen',
            'settings.name': 'Name',
            'settings.email': 'E-Mail',
            'settings.username': 'Benutzername',
            'settings.changePassword': 'Passwort Ändern',
            'settings.currentPassword': 'Aktuelles Passwort',
            'settings.currentPasswordPlaceholder': 'Aktuelles Passwort eingeben',
            'settings.newPassword': 'Neues Passwort',
            'settings.newPasswordPlaceholder': 'Neues Passwort eingeben',
            'settings.confirmPassword': 'Neues Passwort Bestätigen',
            'settings.confirmPasswordPlaceholder': 'Neues Passwort bestätigen',
            'settings.passwordChanged': 'Passwort erfolgreich geändert',
            'settings.failedToChangePassword': 'Fehler beim Ändern des Passworts',
            'settings.invalidCurrentPassword': 'Das aktuelle Passwort ist falsch',
            'settings.passwordTooShort': 'Das Passwort muss mindestens 6 Zeichen lang sein',
            'settings.passwordsDoNotMatch': 'Die neuen Passwörter stimmen nicht überein',
            'settings.newPasswordSame': 'Das neue Passwort muss sich vom aktuellen Passwort unterscheiden',
            'settings.fillAllFields': 'Bitte füllen Sie alle Felder aus',
            'settings.networkError': 'Verbindung zum Server nicht möglich. Stellen Sie sicher, dass der Server läuft.',
            'settings.dangerZone': 'Gefahrenzone',
            'settings.deleteAccountWarning': 'Sobald Sie Ihr Konto löschen, gibt es kein Zurück. Bitte seien Sie sicher.',
  },
  it: {
            'screen.addExpense': 'Aggiungi Spesa',
            'screen.editExpense': 'Modifica Spesa',
            'screen.addIncome': 'Aggiungi Entrata',
            'screen.editIncome': 'Modifica Entrata',
            'screen.scanReceipt': 'Scansiona Ricevuta',
            'screen.reviewReceipt': 'Rivedi Ricevuta',
            'screen.dashboard': 'Cruscotto',
            'screen.categoryBreakdown': 'Ripartizione per Categoria',
            'label.amount': 'Importo',
            'label.date': 'Data',
            'label.merchant': 'Commerciante',
            'label.category': 'Categoria',
            'label.description': 'Descrizione',
            'button.submit': 'Invia',
            'button.saveChanges': 'Salva modifiche',
            'button.addExpense': 'Aggiungi Spesa',
            'button.addIncome': 'Aggiungi Entrata',
            'button.scanReceipt': 'Scansiona ricevuta (prossimamente)',
            'button.ok': 'OK',
            'button.selectCategory': 'Seleziona una categoria',
            'button.deleteExpense': 'Elimina Spesa',
            'button.deleteIncome': 'Elimina Entrata',
            'button.delete': 'Elimina',
            'button.cancel': 'Annulla',
            'button.overview': 'Panoramica',
            'button.income': 'Entrate',
            'button.expenses': 'Spese',
            'message.expenseAdded': 'Spesa aggiunta con successo!',
            'message.expenseUpdated': 'Spesa aggiornata',
            'message.expenseDeleted': 'Spesa eliminata con successo',
            'message.deletingExpense': 'Eliminazione spesa...',
            'message.confirmDelete': 'Sei sicuro di voler eliminare questa spesa? Questa azione non può essere annullata.',
            'message.confirmDeleteIncome': 'Sei sicuro di voler eliminare questa entrata? Questa azione non può essere annullata.',
            'message.incomeAdded': 'Entrata aggiunta con successo!',
            'message.incomeUpdated': 'Entrata aggiornata',
            'message.incomeDeleted': 'Entrata eliminata con successo',
            'message.deletingIncome': 'Eliminazione entrata...',
            'message.success': 'Successo',
            'message.loadingExpense': 'Caricamento spesa...',
            'message.loadingIncome': 'Caricamento entrata...',
            'message.failedToCreate': 'Impossibile creare la spesa',
            'message.failedToUpdate': 'Impossibile aggiornare la spesa',
            'message.failedToDelete': 'Impossibile eliminare la spesa',
            'message.failedToLoad': 'Impossibile caricare la spesa',
            'message.failedToCreateIncome': 'Impossibile creare l\'entrata',
            'message.failedToUpdateIncome': 'Impossibile aggiornare l\'entrata',
            'message.failedToDeleteIncome': 'Impossibile eliminare l\'entrata',
            'message.failedToLoadIncome': 'Impossibile caricare l\'entrata',
            'error.invalidAmount': 'Inserisci un importo valido maggiore di 0',
            'error.selectCategory': 'Seleziona una categoria',
            'error.selectDate': 'Seleziona una data',
            'error.acceptTerms': 'Devi accettare i Termini di Servizio e l\'Informativa sulla Privacy per registrarti',
            'dashboard.currentMonthTotal': 'Totale del Mese Corrente',
            'dashboard.netIncome': 'Reddito Netto',
            'dashboard.totalIncome': 'Entrate Totali',
            'dashboard.totalExpenses': 'Spese Totali',
            'dashboard.monthComparison': 'Confronto Mensile',
            'dashboard.last6Months': 'Ultimi 6 Mesi',
            'dashboard.recentExpenses': 'Spese Recenti',
            'dashboard.recentIncome': 'Entrate Recenti',
            'dashboard.monthlyTotals': 'Totali Mensili',
            'dashboard.noExpenses': 'Nessuna spesa ancora',
            'dashboard.noIncome': 'Nessuna entrata ancora',
            'dashboard.noMonthlyData': 'Nessun dato mensile ancora',
            'dashboard.error': 'Errore',
            'dashboard.tapForDetails': 'Tocca per vedere la ripartizione per categoria',
            'dashboard.categoryBreakdown': 'Ripartizione per Categoria',
            'dashboard.categoryDetails': 'Dettagli Categoria',
            'dashboard.tap': 'Tocca',
            'dashboard.total': 'Totale',
            'dashboard.noData': 'Nessun dato',
            'receipt.scanReceipt': 'Scansiona Ricevuta',
            'receipt.reviewReceipt': 'Rivedi Ricevuta',
            'receipt.processing': 'Elaborazione ricevuta...',
            'receipt.reviewData': 'Rivedi Dati Estratti',
            'receipt.useThisData': 'Usa Questi Dati',
            'receipt.retake': 'Riprendi',
            'receipt.process': 'Elabora',
            'receipt.preview': 'Anteprima',
            'receipt.error': 'Errore',
            'receipt.captureError': 'Impossibile acquisire l\'immagine',
            'receipt.processingError': 'Impossibile elaborare la ricevuta',
            'receipt.extractionFailed': 'Impossibile estrarre i dati dalla ricevuta',
            'receipt.noData': 'Nessun dato estratto',
            'receipt.retry': 'Riprova',
            'receipt.requestingPermission': 'Richiesta autorizzazione fotocamera...',
            'receipt.cameraPermissionDenied': 'Autorizzazione fotocamera negata. Abilitala nelle impostazioni.',
            'receipt.requestPermission': 'Richiedi Autorizzazione',
            'receipt.galleryPermissionDenied': 'Autorizzazione galleria negata. Abilitala nelle impostazioni.',
            'receipt.galleryError': 'Impossibile selezionare l\'immagine dalla galleria',
            'receipt.pickFromGallery': 'Scegli dalla Galleria',
            'receipt.selectReceiptPhoto': 'Seleziona Foto Ricevuta',
            'receipt.webCameraNotSupported': 'La fotocamera non è supportata sul web. Usa "Scegli dalla Galleria" per selezionare un\'immagine.',
            'receipt.merchantPlaceholder': 'Nome del negozio o commerciante',
            'receipt.descriptionPlaceholder': 'Descrizione opzionale',
            'category.groceries': 'Alimentari',
            'category.utilities': 'Utilità',
            'category.transportation': 'Trasporto',
            'category.housing': 'Abitazione',
            'category.healthcare': 'Assistenza Sanitaria',
            'category.education': 'Istruzione',
            'category.entertainment': 'Intrattenimento',
            'category.diningOut': 'Mangiare Fuori',
            'category.clothing': 'Abbigliamento',
            'category.personalCare': 'Cura Personale',
            'category.giftsDonations': 'Regali e Donazioni',
            'category.travel': 'Viaggi',
            'category.loansDebt': 'Prestiti e Pagamenti Debito',
            'category.bankFees': 'Commissioni Bancarie e Scoperti',
            'category.insurance': 'Assicurazione',
            'category.taxes': 'Tasse',
            'category.other': 'Altro',
            'category.salary': 'Stipendio',
            'category.freelance': 'Freelance',
            'category.investment': 'Investimento',
            'category.gift': 'Regalo',
            'category.bonus': 'Bonus',
            'category.otherIncome': 'Altro',
            'placeholder.amount': '0.00',
            'placeholder.description': 'Descrizione opzionale',
            'auth.login': 'Accedi',
            'auth.signup': 'Registrati',
            'auth.email': 'Email',
            'auth.emailPlaceholder': 'tua@email.com',
            'auth.username': 'Nome Utente (opzionale)',
            'auth.usernamePlaceholder': 'nome utente',
            'auth.loginIdentifier': 'Email o Nome Utente',
            'auth.loginIdentifierPlaceholder': 'email o nome utente',
            'auth.password': 'Password',
            'auth.passwordPlaceholder': 'Inserisci la password',
            'auth.name': 'Nome',
            'auth.namePlaceholder': 'Il tuo nome',
            'auth.haveAccount': 'Hai già un account? Accedi',
            'auth.noAccount': 'Non hai un account? Registrati',
            'auth.forgotPassword': 'Password dimenticata?',
            'auth.resetPassword': 'Reimposta Password',
            'auth.resetPasswordTitle': 'Reimposta la Tua Password',
            'auth.resetPasswordMessage': 'Inserisci il tuo indirizzo email e ti invieremo le istruzioni per reimpostare la tua password.',
            'auth.resetPasswordSent': 'Se esiste un account con questa email, sono state inviate istruzioni per reimpostare la password.',
            'auth.backToLogin': 'Torna al Login',
            'auth.acceptTerms1': 'Accetto i',
            'auth.termsOfService': 'Termini di Servizio',
            'auth.and': 'e',
            'auth.privacyPolicy': 'Informativa sulla Privacy',
            'auth.deleteAccount': 'Elimina Account',
            'auth.confirmDeleteAccount': 'Sei sicuro di voler eliminare il tuo account? Questo eliminerà permanentemente tutti i tuoi dati, inclusi tutte le spese. Questa azione non può essere annullata.',
            'auth.failedToDeleteAccount': 'Impossibile eliminare l\'account. Riprova.',
            'auth.error': 'Errore',
            'screen.settings': 'Impostazioni',
            'settings.openSettings': 'Apri Impostazioni',
            'settings.selectLanguage': 'Seleziona Lingua',
            'settings.accountInfo': 'Informazioni Account',
            'settings.name': 'Nome',
            'settings.email': 'Email',
            'settings.username': 'Nome Utente',
            'settings.changePassword': 'Cambia Password',
            'settings.currentPassword': 'Password Attuale',
            'settings.currentPasswordPlaceholder': 'Inserisci la password attuale',
            'settings.newPassword': 'Nuova Password',
            'settings.newPasswordPlaceholder': 'Inserisci la nuova password',
            'settings.confirmPassword': 'Conferma Nuova Password',
            'settings.confirmPasswordPlaceholder': 'Conferma la nuova password',
            'settings.passwordChanged': 'Password modificata con successo',
            'settings.failedToChangePassword': 'Impossibile modificare la password',
            'settings.invalidCurrentPassword': 'La password attuale è errata',
            'settings.passwordTooShort': 'La password deve contenere almeno 6 caratteri',
            'settings.passwordsDoNotMatch': 'Le nuove password non corrispondono',
            'settings.newPasswordSame': 'La nuova password deve essere diversa dalla password attuale',
            'settings.fillAllFields': 'Compila tutti i campi',
            'settings.networkError': 'Impossibile connettersi al server. Assicurati che il server sia in esecuzione.',
            'settings.dangerZone': 'Zona Pericolosa',
            'settings.deleteAccountWarning': 'Una volta eliminato il tuo account, non c\'è modo di tornare indietro. Sii certo.',
  },
  ar: {
            'screen.addExpense': 'إضافة مصروف',
            'screen.editExpense': 'تعديل مصروف',
            'screen.addIncome': 'إضافة دخل',
            'screen.editIncome': 'تعديل دخل',
            'screen.scanReceipt': 'مسح الإيصال',
            'screen.reviewReceipt': 'مراجعة الإيصال',
            'screen.dashboard': 'لوحة التحكم',
            'screen.categoryBreakdown': 'التفصيل حسب الفئة',
            'label.amount': 'المبلغ',
            'label.date': 'التاريخ',
            'label.merchant': 'التاجر',
            'label.category': 'الفئة',
            'label.description': 'الوصف',
            'button.submit': 'إرسال',
            'button.saveChanges': 'حفظ التغييرات',
            'button.addExpense': 'إضافة مصروف',
            'button.addIncome': 'إضافة دخل',
            'button.scanReceipt': 'مسح الإيصال (قريباً)',
            'button.ok': 'موافق',
            'button.selectCategory': 'اختر فئة',
            'button.deleteExpense': 'حذف مصروف',
            'button.deleteIncome': 'حذف دخل',
            'button.delete': 'حذف',
            'button.cancel': 'إلغاء',
            'button.overview': 'نظرة عامة',
            'button.income': 'الدخل',
            'button.expenses': 'المصروفات',
            'message.expenseAdded': 'تم إضافة المصروف بنجاح!',
            'message.expenseUpdated': 'تم تحديث المصروف',
            'message.expenseDeleted': 'تم حذف المصروف بنجاح',
            'message.deletingExpense': 'جاري حذف المصروف...',
            'message.confirmDelete': 'هل أنت متأكد من رغبتك في حذف هذا المصروف؟ لا يمكن التراجع عن هذا الإجراء.',
            'message.confirmDeleteIncome': 'هل أنت متأكد من رغبتك في حذف هذا الدخل؟ لا يمكن التراجع عن هذا الإجراء.',
            'message.incomeAdded': 'تم إضافة الدخل بنجاح!',
            'message.incomeUpdated': 'تم تحديث الدخل',
            'message.incomeDeleted': 'تم حذف الدخل بنجاح',
            'message.deletingIncome': 'جاري حذف الدخل...',
            'message.success': 'نجح',
            'message.loadingExpense': 'جاري تحميل المصروف...',
            'message.loadingIncome': 'جاري تحميل الدخل...',
            'message.failedToCreate': 'فشل في إنشاء المصروف',
            'message.failedToUpdate': 'فشل في تحديث المصروف',
            'message.failedToDelete': 'فشل في حذف المصروف',
            'message.failedToLoad': 'فشل في تحميل المصروف',
            'message.failedToCreateIncome': 'فشل في إنشاء الدخل',
            'message.failedToUpdateIncome': 'فشل في تحديث الدخل',
            'message.failedToDeleteIncome': 'فشل في حذف الدخل',
            'message.failedToLoadIncome': 'فشل في تحميل الدخل',
            'error.invalidAmount': 'يرجى إدخال مبلغ صالح أكبر من 0',
            'error.selectCategory': 'يرجى اختيار فئة',
            'error.selectDate': 'يرجى اختيار تاريخ',
            'error.acceptTerms': 'يجب عليك قبول شروط الخدمة وسياسة الخصوصية للتسجيل',
            'dashboard.currentMonthTotal': 'إجمالي الشهر الحالي',
            'dashboard.netIncome': 'صافي الدخل',
            'dashboard.totalIncome': 'إجمالي الدخل',
            'dashboard.totalExpenses': 'إجمالي المصروفات',
            'dashboard.monthComparison': 'مقارنة الشهر',
            'dashboard.last6Months': 'آخر 6 أشهر',
            'dashboard.recentExpenses': 'المصروفات الأخيرة',
            'dashboard.recentIncome': 'الدخل الأخير',
            'dashboard.monthlyTotals': 'الإجماليات الشهرية',
            'dashboard.noExpenses': 'لا توجد مصروفات بعد',
            'dashboard.noIncome': 'لا يوجد دخل بعد',
            'dashboard.noMonthlyData': 'لا توجد بيانات شهرية بعد',
            'dashboard.error': 'خطأ',
            'dashboard.tapForDetails': 'اضغط لرؤية التفصيل حسب الفئة',
            'dashboard.categoryBreakdown': 'التفصيل حسب الفئة',
            'dashboard.categoryDetails': 'تفاصيل الفئة',
            'dashboard.tap': 'اضغط',
            'dashboard.total': 'الإجمالي',
            'dashboard.noData': 'لا توجد بيانات',
            'receipt.scanReceipt': 'مسح الإيصال',
            'receipt.reviewReceipt': 'مراجعة الإيصال',
            'receipt.processing': 'جاري معالجة الإيصال...',
            'receipt.reviewData': 'مراجعة البيانات المستخرجة',
            'receipt.useThisData': 'استخدم هذه البيانات',
            'receipt.retake': 'إعادة التقاط',
            'receipt.process': 'معالجة',
            'receipt.preview': 'معاينة',
            'receipt.error': 'خطأ',
            'receipt.captureError': 'فشل في التقاط الصورة',
            'receipt.processingError': 'فشل في معالجة الإيصال',
            'receipt.extractionFailed': 'فشل في استخراج البيانات من الإيصال',
            'receipt.noData': 'لم يتم استخراج بيانات',
            'receipt.retry': 'إعادة المحاولة',
            'receipt.requestingPermission': 'جاري طلب إذن الكاميرا...',
            'receipt.cameraPermissionDenied': 'تم رفض إذن الكاميرا. يرجى تفعيله في الإعدادات.',
            'receipt.requestPermission': 'طلب الإذن',
            'receipt.galleryPermissionDenied': 'تم رفض إذن المعرض. يرجى تفعيله في الإعدادات.',
            'receipt.galleryError': 'فشل في اختيار الصورة من المعرض',
            'receipt.pickFromGallery': 'اختر من المعرض',
            'receipt.selectReceiptPhoto': 'اختر صورة الإيصال',
            'receipt.webCameraNotSupported': 'الكاميرا غير مدعومة على الويب. يرجى استخدام "اختر من المعرض" لاختيار صورة.',
            'receipt.merchantPlaceholder': 'اسم المتجر أو التاجر',
            'receipt.descriptionPlaceholder': 'وصف اختياري',
            'category.groceries': 'البقالة',
            'category.utilities': 'المرافق',
            'category.transportation': 'المواصلات',
            'category.housing': 'السكن',
            'category.healthcare': 'الرعاية الصحية',
            'category.education': 'التعليم',
            'category.entertainment': 'الترفيه',
            'category.diningOut': 'تناول الطعام خارجاً',
            'category.clothing': 'الملابس',
            'category.personalCare': 'العناية الشخصية',
            'category.giftsDonations': 'الهدايا والتبرعات',
            'category.travel': 'السفر',
            'category.loansDebt': 'القروض ودفع الديون',
            'category.bankFees': 'رسوم البنك والمديونية',
            'category.insurance': 'التأمين',
            'category.taxes': 'الضرائب',
            'category.other': 'أخرى',
            'category.salary': 'الراتب',
            'category.freelance': 'العمل الحر',
            'category.investment': 'الاستثمار',
            'category.gift': 'هدية',
            'category.bonus': 'مكافأة',
            'category.otherIncome': 'أخرى',
            'placeholder.amount': '0.00',
            'placeholder.description': 'وصف اختياري',
            'auth.login': 'تسجيل الدخول',
            'auth.signup': 'إنشاء حساب',
            'auth.email': 'البريد الإلكتروني',
            'auth.emailPlaceholder': 'your@email.com',
            'auth.username': 'اسم المستخدم (اختياري)',
            'auth.usernamePlaceholder': 'اسم المستخدم',
            'auth.loginIdentifier': 'البريد الإلكتروني أو اسم المستخدم',
            'auth.loginIdentifierPlaceholder': 'البريد الإلكتروني أو اسم المستخدم',
            'auth.password': 'كلمة المرور',
            'auth.passwordPlaceholder': 'أدخل كلمة المرور',
            'auth.name': 'الاسم',
            'auth.namePlaceholder': 'اسمك',
            'auth.haveAccount': 'لديك حساب بالفعل؟ تسجيل الدخول',
            'auth.noAccount': 'ليس لديك حساب؟ إنشاء حساب',
            'auth.forgotPassword': 'نسيت كلمة المرور؟',
            'auth.resetPassword': 'إعادة تعيين كلمة المرور',
            'auth.resetPasswordTitle': 'أعد تعيين كلمة المرور',
            'auth.resetPasswordMessage': 'أدخل عنوان بريدك الإلكتروني وسنرسل لك تعليمات إعادة تعيين كلمة المرور.',
            'auth.resetPasswordSent': 'إذا كان هناك حساب بهذا البريد الإلكتروني، تم إرسال تعليمات إعادة تعيين كلمة المرور.',
            'auth.backToLogin': 'العودة لتسجيل الدخول',
            'auth.acceptTerms1': 'أوافق على',
            'auth.termsOfService': 'شروط الخدمة',
            'auth.and': 'و',
            'auth.privacyPolicy': 'سياسة الخصوصية',
            'auth.deleteAccount': 'حذف الحساب',
            'auth.confirmDeleteAccount': 'هل أنت متأكد من رغبتك في حذف حسابك؟ سيؤدي هذا إلى حذف جميع بياناتك بشكل دائم بما في ذلك جميع المصروفات. لا يمكن التراجع عن هذا الإجراء.',
            'auth.failedToDeleteAccount': 'فشل في حذف الحساب. يرجى المحاولة مرة أخرى.',
            'auth.error': 'خطأ',
            'screen.settings': 'الإعدادات',
            'settings.openSettings': 'فتح الإعدادات',
            'settings.selectLanguage': 'اختر اللغة',
            'settings.accountInfo': 'معلومات الحساب',
            'settings.name': 'الاسم',
            'settings.email': 'البريد الإلكتروني',
            'settings.username': 'اسم المستخدم',
            'settings.changePassword': 'تغيير كلمة المرور',
            'settings.currentPassword': 'كلمة المرور الحالية',
            'settings.currentPasswordPlaceholder': 'أدخل كلمة المرور الحالية',
            'settings.newPassword': 'كلمة المرور الجديدة',
            'settings.newPasswordPlaceholder': 'أدخل كلمة المرور الجديدة',
            'settings.confirmPassword': 'تأكيد كلمة المرور الجديدة',
            'settings.confirmPasswordPlaceholder': 'أكد كلمة المرور الجديدة',
            'settings.passwordChanged': 'تم تغيير كلمة المرور بنجاح',
            'settings.failedToChangePassword': 'فشل في تغيير كلمة المرور',
            'settings.invalidCurrentPassword': 'كلمة المرور الحالية غير صحيحة',
            'settings.passwordTooShort': 'يجب أن تكون كلمة المرور 6 أحرف على الأقل',
            'settings.passwordsDoNotMatch': 'كلمات المرور الجديدة غير متطابقة',
            'settings.newPasswordSame': 'يجب أن تكون كلمة المرور الجديدة مختلفة عن كلمة المرور الحالية',
            'settings.fillAllFields': 'يرجى ملء جميع الحقول',
            'settings.networkError': 'لا يمكن الاتصال بالخادم. تأكد من أن الخادم قيد التشغيل.',
            'settings.dangerZone': 'منطقة الخطر',
            'settings.deleteAccountWarning': 'بمجرد حذف حسابك، لا يمكن التراجع. يرجى التأكد.',
  },
};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState('en');
  const [isLoading, setIsLoading] = useState(true);

  // Load saved language on mount
  useEffect(() => {
    loadSavedLanguage();
  }, []);

  const loadSavedLanguage = async () => {
    try {
      if (!AsyncStorage) {
        setIsLoading(false);
        return;
      }
      const savedLanguage = await AsyncStorage.getItem(STORAGE_KEY).catch(err => {
        console.error('Error reading language:', err);
        return null;
      });
      if (savedLanguage && translations[savedLanguage]) {
        setLanguage(savedLanguage);
      }
    } catch (error) {
      console.error('Error loading saved language:', error);
      // Continue with default language
    } finally {
      setIsLoading(false);
    }
  };

  const handleSetLanguage = async (newLanguage) => {
    if (translations[newLanguage]) {
      setLanguage(newLanguage);
      try {
        await AsyncStorage.setItem(STORAGE_KEY, newLanguage);
      } catch (error) {
        console.error('Error saving language:', error);
      }
    }
  };

  const t = (key) => {
    return translations[language]?.[key] || translations.en?.[key] || key;
  };

  // Show loading indicator while language is loading
  if (isLoading) {
    return (
      <View style={{ flex: 1, justifyContent: 'center', alignItems: 'center' }}>
        <ActivityIndicator size="large" />
      </View>
    );
  }

  return (
    <LanguageContext.Provider value={{ language, setLanguage: handleSetLanguage, t, languages }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

